
[build]
	command = "npm run build"
	publish = "dist"

[dev]
	command = "npm run dev"
	port = 8888

[context.production.environment]
	NODE_VERSION = "18"

[context.deploy-preview.environment]
	NODE_VERSION = "18"
